// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDwBNM-CquuebYuEB2avWklz4ErGIaEY4',
    appId: '1:770388969907:web:a3049db716ef2d6c9663c6',
    messagingSenderId: '770388969907',
    projectId: 'green-cycle-2a62e',
    authDomain: 'green-cycle-2a62e.firebaseapp.com',
    storageBucket: 'green-cycle-2a62e.appspot.com',
    measurementId: 'G-VX7MYXCFM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiOd0il67Hp1VzY9bPLltabetXRwLuaA4',
    appId: '1:770388969907:android:e1467b973d7c88639663c6',
    messagingSenderId: '770388969907',
    projectId: 'green-cycle-2a62e',
    storageBucket: 'green-cycle-2a62e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeH3ymBkMwaHrbQEVJjL8ay36OWKG1K0Y',
    appId: '1:770388969907:ios:720ee8ff8a6e6f969663c6',
    messagingSenderId: '770388969907',
    projectId: 'green-cycle-2a62e',
    storageBucket: 'green-cycle-2a62e.appspot.com',
    iosBundleId: 'com.example.greenCycleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeH3ymBkMwaHrbQEVJjL8ay36OWKG1K0Y',
    appId: '1:770388969907:ios:c6acd2656676861d9663c6',
    messagingSenderId: '770388969907',
    projectId: 'green-cycle-2a62e',
    storageBucket: 'green-cycle-2a62e.appspot.com',
    iosBundleId: 'com.example.greenCycleApp.RunnerTests',
  );
}
